name: redux
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Brian Egan <brian@brianegan.com>
description: Redux is a predictable state container for Dart and Flutter apps
homepage: https://github.com/johnpryan/redux.dart
version: 4.0.0

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: '>=1.0.0 <2.0.0'
  pedantic: ">=1.8.0+1 <2.0.0"
  coverage: ">=0.13.0 <0.14.0"
