name: redux
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Brian Egan <brian@brianegan.com>
description: Redux for Dart
homepage: http://github.com/johnpryan/redux.dart
version: 2.0.0

dev_dependencies:
  browser: any
  test: any
